//! [`ApprovalGate`]: the answering half.

use std::sync::Arc;
use std::sync::atomic::Ordering;

use aik_api::permission::PermissionRequest;
use aik_core::clock::Timestamp;
use aik_core::id::CorrelationId;
use aik_core::{Error, Result};
use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;

use crate::broker::Shared;

aik_core::uuid_id! {
    /// Identifies one question awaiting an answer.
    ///
    /// Generated by the broker and given to the frontend, which quotes it back to answer.
    /// An answer is therefore always about exactly one request: ids are never reused, and a
    /// question is removed from the queue the moment it is answered, abandoned or expires.
    pub ApprovalId
}

/// A question awaiting a human's answer.
///
/// This is everything a frontend needs to render a prompt, and deliberately nothing more.
/// Notably absent are the tool's arguments: the bytes of a `filesystem.write` are not what
/// makes the decision, and a prompt that displayed them would put model-authored content in
/// front of a person who is about to click "allow" — see [`PendingApproval::prompt`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PendingApproval {
    /// What to quote back when answering.
    pub id: ApprovalId,

    /// The question, as the policy engine was asked it: who, what action, what resource.
    pub request: PermissionRequest,

    /// The text to show the human.
    ///
    /// Authored by the policy engine — the same trusted, human-facing text as a
    /// [`Decision::Deny`](aik_api::permission::Decision::Deny) reason — and never by a model
    /// or a tool. A frontend should present it as the *question*, and take the concrete
    /// action and resource from [`PendingApproval::request`], which the policy engine did
    /// not write.
    pub prompt: String,

    /// The operation this question belongs to, for correlating with audit events.
    pub correlation: CorrelationId,

    /// When the question was asked.
    pub requested_at: Timestamp,

    /// When it gives up, after which answering it does nothing.
    ///
    /// A frontend should show this: an approval prompt is only meaningful while somebody is
    /// still waiting for it.
    pub expires_at: Timestamp,
}

/// The handle a frontend answers questions through.
///
/// Obtained from [`ApprovalBroker::gate`](crate::ApprovalBroker::gate). Holding one is an
/// assertion that questions will actually be put to a human: while at least one gate exists
/// the broker parks questions and waits, and when the last one is dropped it refuses them
/// immediately instead.
///
/// Cloning yields another handle to the same broker and counts as another responder, so a
/// clone must be dropped when that responder goes away. Every method is non-blocking.
///
/// # This is a trusted capability
///
/// Anything holding a gate can approve anything, including on behalf of the agent whose
/// request it is. Give it to the frontend that asks the human, and to nothing else — an
/// agent that could reach a gate could approve its own escalation, which would make the
/// whole mechanism decorative.
pub struct ApprovalGate {
    shared: Arc<Shared>,
}

impl std::fmt::Debug for ApprovalGate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ApprovalGate")
            .field("pending", &self.pending().len())
            .field("gates", &self.shared.gates.load(Ordering::SeqCst))
            .finish()
    }
}

impl Clone for ApprovalGate {
    fn clone(&self) -> Self {
        Self::attach(self.shared.clone())
    }
}

impl Drop for ApprovalGate {
    fn drop(&mut self) {
        self.shared.gates.fetch_sub(1, Ordering::SeqCst);
    }
}

impl ApprovalGate {
    pub(crate) fn attach(shared: Arc<Shared>) -> Self {
        shared.gates.fetch_add(1, Ordering::SeqCst);
        Self { shared }
    }

    /// Every question currently awaiting an answer, oldest first.
    ///
    /// This is the authoritative view: a frontend that missed a notification, or that
    /// attached after a question was asked, recovers everything from here.
    pub fn pending(&self) -> Vec<PendingApproval> {
        let mut pending: Vec<PendingApproval> = match self.shared.waiting.lock() {
            Ok(waiting) => waiting
                .values()
                .map(|waiter| waiter.pending.clone())
                .collect(),
            Err(poisoned) => poisoned
                .into_inner()
                .values()
                .map(|waiter| waiter.pending.clone())
                .collect(),
        };
        // Ids are UUIDv7, so ordering by id is ordering by creation even when two questions
        // share a millisecond.
        pending.sort_by_key(|entry| (entry.requested_at, entry.id));
        pending
    }

    /// Grants one question.
    ///
    /// # Errors
    ///
    /// [`Error::NotFound`] if the question is no longer waiting — already answered, expired,
    /// abandoned by the requester, or from a closed broker. A late grant has no effect: the
    /// operation it would have permitted has already been refused.
    pub fn approve(&self, id: &ApprovalId) -> Result<()> {
        self.answer(id, true)
    }

    /// Refuses one question.
    ///
    /// # Errors
    ///
    /// As [`ApprovalGate::approve`]; a late refusal is equally inconsequential, since giving
    /// up already refused it.
    pub fn deny(&self, id: &ApprovalId) -> Result<()> {
        self.answer(id, false)
    }

    /// Watches for new questions.
    ///
    /// The stream holds a gate of its own, so a frontend cannot accidentally detach itself
    /// by dropping the handle it subscribed through while still listening.
    ///
    /// Notifications are lossy under load; [`ApprovalGate::pending`] is not. A frontend that
    /// wants to be correct as well as prompt reconciles against `pending()` — the stream is
    /// a wake-up, not a queue.
    pub fn subscribe(&self) -> ApprovalStream {
        ApprovalStream {
            receiver: self.shared.notifications.subscribe(),
            gate: self.clone(),
        }
    }

    fn answer(&self, id: &ApprovalId, granted: bool) -> Result<()> {
        let waiter = self
            .shared
            .withdraw(id)
            .ok_or_else(|| Error::not_found("pending approval", id))?;

        // The requester stopped waiting between the lookup and now. Report it rather than
        // claiming success: nothing was permitted, and a frontend that showed "approved"
        // would be describing something that did not happen.
        waiter
            .answer
            .send(granted)
            .map_err(|_| Error::not_found("pending approval", id))
    }
}

/// A subscription to newly asked questions.
///
/// Dropping it stops the notifications and releases the gate it holds.
#[derive(Debug)]
pub struct ApprovalStream {
    receiver: broadcast::Receiver<PendingApproval>,
    gate: ApprovalGate,
}

impl ApprovalStream {
    /// Waits for the next question, or returns `None` once the broker is gone.
    ///
    /// Lag is skipped rather than reported: a missed notification is recoverable through
    /// [`ApprovalGate::pending`], and a frontend that has to handle "you missed some" at
    /// every call site tends to handle it by ignoring it.
    pub async fn recv(&mut self) -> Option<PendingApproval> {
        loop {
            match self.receiver.recv().await {
                Ok(pending) => return Some(pending),
                Err(broadcast::error::RecvError::Closed) => return None,
                Err(broadcast::error::RecvError::Lagged(count)) => {
                    tracing::warn!(
                        missed = count,
                        "approval notifications lagged; reconcile with `pending()`"
                    );
                }
            }
        }
    }

    /// The gate this subscription answers through.
    pub fn gate(&self) -> &ApprovalGate {
        &self.gate
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ApprovalBroker;
    use aik_api::execution::ExecutionContext;
    use aik_api::permission::{ActionId, ApprovalSink, Principal, PrincipalKind, ResourceId};
    use std::time::Duration;

    fn question(resource: &str) -> PermissionRequest {
        PermissionRequest {
            principal: Principal::new("agent-1", PrincipalKind::Agent),
            action: ActionId::new("filesystem.write"),
            resource: Some(ResourceId::new(resource)),
            context: serde_json::Value::Null,
        }
    }

    #[tokio::test(start_paused = true)]
    async fn an_approved_question_is_granted_and_a_denied_one_is_not() {
        for granted in [true, false] {
            let broker = Arc::new(ApprovalBroker::new());
            let gate = broker.gate();

            let asking = tokio::spawn({
                let broker = broker.clone();
                async move {
                    broker
                        .request_approval(&question("/tmp/a"), "may I?", &ExecutionContext::new())
                        .await
                }
            });
            tokio::time::sleep(Duration::from_millis(10)).await;

            let pending = gate.pending();
            assert_eq!(pending.len(), 1);
            assert_eq!(pending[0].prompt, "may I?");
            assert_eq!(
                pending[0].request.resource.as_ref().unwrap().as_str(),
                "/tmp/a"
            );

            if granted {
                gate.approve(&pending[0].id).unwrap();
            } else {
                gate.deny(&pending[0].id).unwrap();
            }

            assert_eq!(asking.await.unwrap().unwrap(), granted);
            assert!(gate.pending().is_empty());
        }
    }

    #[tokio::test(start_paused = true)]
    async fn answering_one_question_leaves_the_others_waiting() {
        let broker = Arc::new(ApprovalBroker::new());
        let gate = broker.gate();

        let mut asking = Vec::new();
        for path in ["/tmp/a", "/tmp/b"] {
            let broker = broker.clone();
            asking.push(tokio::spawn(async move {
                broker
                    .request_approval(&question(path), "may I?", &ExecutionContext::new())
                    .await
            }));
        }
        tokio::time::sleep(Duration::from_millis(10)).await;

        let pending = gate.pending();
        assert_eq!(pending.len(), 2);
        let first = pending
            .iter()
            .find(|entry| entry.request.resource.as_ref().unwrap().as_str() == "/tmp/a")
            .unwrap();
        gate.approve(&first.id).unwrap();

        let remaining = gate.pending();
        assert_eq!(remaining.len(), 1);
        assert_eq!(
            remaining[0].request.resource.as_ref().unwrap().as_str(),
            "/tmp/b"
        );
    }

    #[tokio::test]
    async fn answering_an_unknown_question_fails() {
        let broker = ApprovalBroker::new();
        let gate = broker.gate();
        let error = gate.approve(&ApprovalId::new()).unwrap_err();
        assert!(matches!(error, Error::NotFound { .. }), "{error}");
    }

    #[tokio::test(start_paused = true)]
    async fn an_answer_after_the_requester_gave_up_changes_nothing() {
        let broker = Arc::new(ApprovalBroker::with_settings(crate::ApprovalSettings {
            timeout: Duration::from_secs(1),
            ..Default::default()
        }));
        let gate = broker.gate();

        let asking = tokio::spawn({
            let broker = broker.clone();
            async move {
                broker
                    .request_approval(&question("/tmp/a"), "may I?", &ExecutionContext::new())
                    .await
            }
        });
        tokio::time::sleep(Duration::from_millis(10)).await;
        let id = gate.pending()[0].id;

        // The request times out while nobody answers…
        let error = asking.await.unwrap().unwrap_err();
        assert!(matches!(error, Error::Timeout(_)), "{error}");

        // …so a grant that arrives afterwards has nothing to permit.
        let error = gate.approve(&id).unwrap_err();
        assert!(matches!(error, Error::NotFound { .. }), "{error}");
        assert!(gate.pending().is_empty());
    }

    #[tokio::test(start_paused = true)]
    async fn a_subscriber_is_woken_by_a_new_question() {
        let broker = Arc::new(ApprovalBroker::new());
        let gate = broker.gate();
        let mut stream = gate.subscribe();

        tokio::spawn({
            let broker = broker.clone();
            async move {
                broker
                    .request_approval(&question("/tmp/a"), "may I?", &ExecutionContext::new())
                    .await
            }
        });

        let pending = stream.recv().await.unwrap();
        assert_eq!(pending.request.resource.unwrap().as_str(), "/tmp/a");
        stream.gate().deny(&pending.id).unwrap();
    }

    #[tokio::test]
    async fn a_stream_keeps_the_gate_attached() {
        let broker = ApprovalBroker::new();
        let stream = broker.gate().subscribe();
        assert_eq!(broker.gate_count(), 1);
        drop(stream);
        assert_eq!(broker.gate_count(), 0);
    }

    #[test]
    fn pending_approvals_survive_a_round_trip_to_json() {
        let pending = PendingApproval {
            id: ApprovalId::new(),
            request: question("/tmp/a"),
            prompt: "may I?".into(),
            correlation: CorrelationId::new(),
            requested_at: Timestamp::from_millis(1_000),
            expires_at: Timestamp::from_millis(2_000),
        };
        let json = serde_json::to_value(&pending).unwrap();
        assert_eq!(json["prompt"], serde_json::json!("may I?"));
        assert_eq!(
            serde_json::from_value::<PendingApproval>(json).unwrap(),
            pending
        );
    }
}
